### ISSUE TITLE
Send Password

### ISSUE THREAD

**Issue by ddkwork** [fyne-io/terminal#17]
Hello teacher, how to send user password with multiline commands? Simple:

func autoComplete(commands string){
	terminal.write string(commands)
	terminal.run()
}

func main(){
	commands:='
	su root
	password:123456
	pacman -S go
	pacman -S clang
	'
	autoComplete(commands)
}

**Comment by andydotxyz** [comment]
I don't quite know the context so it's not clear what you are aiming to do.
A terminal sends characters to the program running within it. The program gets the events and decides what to do with them.
So if your application is expecting a password it will not appear.

Your code will need to be more intelligent to execute commands one at a time, send keystrokes once they are responding, then progress with the next one, otherwise all of that text will be dumped to your shell program in one go.

**Comment by DiskGetor** [comment]
> I don't quite know the context so it's not clear what you are aiming to do.
> A terminal sends characters to the program running within it. The program gets the events and decides what to do with them.
> So if your application is expecting a password it will not appear.
> 
> Your code will need to be more intelligent to execute commands one at a time, send keystrokes once they are responding, then progress with the next one, otherwise all of that text will be dumped to your shell program in one go.

Hello,when i install windows and linux system late every time, the first thing i must input more and more repeated commands install application for develop environment, so i aways write a script for do that. I must input $user password on shell app window on linux. And the long time late,more and more scripts will be writes, because theier function is different,so i can't meage them. Finally i think the best way is use your terminal pkg do this.

**Comment by ddkwork** [comment]
> I don't quite know the context so it's not clear what you are aiming to do.
> A terminal sends characters to the program running within it. The program gets the events and decides what to do with them.
> So if your application is expecting a password it will not appear.
> 
> Your code will need to be more intelligent to execute commands one at a time, send keystrokes once they are responding, then progress with the next one, otherwise all of that text will be dumped to your shell program in one go.

Hello again, if embed terminal to app, the focus aways losted, so please add terminal as a widget to fyne internal widget, another problem is can you add and  export  a named mainWindow field, it aways used in dialog and focus.

![Screenshot_20210713_012124_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/125330972-fb347880-e379-11eb-8d97-2ee8d43979dc.jpg)
![Screenshot_20210713_012146_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/125330980-fd96d280-e379-11eb-8ec7-5865dd7f80cc.jpg)

**Comment by andydotxyz** [comment]
> Hello again for you, if embed terminal to app, the focus aways losted, so please add terminal as a widget to fyne internal widget

I do not understand this. Widgets are not created focused, you need to call `Canvas.Focus(myObj)` or have the user focus it with `Tab` key or mouse tap.

> another problem is can you add and export a named mainWindow field, it aways used in dialog and focus.

As the application developer you create the window, so you should be able to save a reference for use later.

**Comment by andydotxyz** [comment]
It sounds like the issue was concluded, closing ticket.

**Comment by ddkwork** [comment]
> It sounds like the issue was concluded, closing ticket.

Sorry, my test look like is a bug.
![Screenshot_20210713_093359_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/125376810-5be5a480-e3be-11eb-9a96-2fb83c4698f8.jpg)

**Comment by andydotxyz** [comment]
What is the bug? The title is “send password”

**Comment by ddkwork** [comment]
> What is the bug? The title is “send password”

Apptab or tree focus when onselected fn test falid.

**Comment by andydotxyz** [comment]
AppTabs and Tree do not have any focus code, I'm not sure what you mean.
