### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by blackfox1983** [fyne-io/terminal#18]
I write a ssh server, and run ssh-client named 'SecureCRT' well. but when i use this library to build a application, it show some errors like
1. unknown escape, for example, 12、1……
2. when run top、ps aux……，the text on terminal will disorder.
so, I'd like to know if this project is still going on 

thanks

**Comment by Jacalz** [comment]
Yes, this project is alive. The latest commits were at the end of October, only two months ago.

The time on these projects are shared with all of the other Fyne projects. That is not always a bad thing though, because some of the changes upstream in Fyne will eventually trickle down and improve the performance here. If you, or anyone you know, are interested in improving this or any other project, feel free to open a PR or post bug reports. It is open source after all. Any help is appreciated :)

**Comment by andydotxyz** [comment]
Point 2 is a duplicate of #9, which happened in some optimisation code - it seems that resizing can mess it up
